/**
 * composables/useGraph.ts
 * Core graph data structure — the single source of truth for the adjacency list.
 *
 * Responsibilities (single): graph storage, edge management, BFS algorithms.
 * No knowledge of Vue UI, components, auth state, or recommendations.
 *
 * Layer: Service (graph algorithms only)
 */
import { ref, reactive } from 'vue'
import type { GraphStats, PathResult } from '@/types'
import { recalculateGraphInsights } from '@/composables/useGraphInsights'

// ─── Module-level singleton ────────────────────────────────────────────────────
// All composables and components share the same reactive graph instance.

export const graph = ref<Map<string, Set<string>>>(new Map())

export const stats = reactive<GraphStats>({
  studentsCount: 0,
  interestsCount: 0,
  activitiesCount: 0,
  componentsCount: 0,
})

// ─── Node Key Formatting ───────────────────────────────────────────────────────

/** Formats a typed node key. Matches campus_buddy.py convention: 'kind:name' */
export const nodeKey = (kind: string, name: string): string => `${kind}:${name}`

/** Returns all interest node ids adjacent to a given graph node */
export const getNodeInterests = (nodeId: string): string[] =>
  Array.from(graph.value.get(nodeId) ?? []).filter(n => n.startsWith('interest:'))

// ─── Edge Management ──────────────────────────────────────────────────────────

/** Adds an undirected edge between u and v in the adjacency-list graph */
export const addEdge = (u: string, v: string): void => {
  if (!graph.value.has(u)) graph.value.set(u, new Set())
  if (!graph.value.has(v)) graph.value.set(v, new Set())
  graph.value.get(u)!.add(v)
  graph.value.get(v)!.add(u)
}

// ─── BFS: Connected Components (private) ──────────────────────────────────────

const _countConnectedComponents = (): number => {
  const visited = new Set<string>()
  let count = 0
  for (const node of graph.value.keys()) {
    if (visited.has(node)) continue
    count++
    const queue = [node]
    visited.add(node)
    while (queue.length > 0) {
      const current = queue.shift()!
      for (const neighbor of graph.value.get(current) ?? []) {
        if (!visited.has(neighbor)) {
          visited.add(neighbor)
          queue.push(neighbor)
        }
      }
    }
  }
  return count
}

// ─── Stats ────────────────────────────────────────────────────────────────────

/** Recalculates node-type counts and connected component count */
export const updateStats = (): void => {
  let s = 0, i = 0, a = 0
  for (const node of graph.value.keys()) {
    if (node.startsWith('student:'))       s++
    else if (node.startsWith('interest:')) i++
    else if (node.startsWith('activity:')) a++
  }
  stats.studentsCount   = s
  stats.interestsCount  = i
  stats.activitiesCount = a
  stats.componentsCount = _countConnectedComponents()
  recalculateGraphInsights()
}

// ─── BFS: Shortest Path (六度分隔 / Six Degrees of Separation) ───────────────

/**
 * BFS shortest path between two students through the heterogeneous graph.
 * Demonstrates the "six degrees of separation" concept.
 * Returns null if either student doesn't exist or no path is found.
 */
export const findPath = (studentA: string, studentB: string): PathResult | null => {
  const start = nodeKey('student', studentA)
  const end   = nodeKey('student', studentB)

  if (!graph.value.has(start) || !graph.value.has(end)) return null
  if (start === end) return { path: [start], hops: 0, readable: [studentA] }

  const queue: [string, string[]][] = [[start, [start]]]
  const visited = new Set<string>([start])

  while (queue.length > 0) {
    const [current, path] = queue.shift()!
    for (const neighbor of graph.value.get(current) ?? []) {
      if (visited.has(neighbor)) continue
      const newPath = [...path, neighbor]
      if (neighbor === end) {
        const hops = newPath.filter(n => n.startsWith('student:')).length - 1
        return { path: newPath, hops, readable: newPath.map(n => n.split(':')[1]) }
      }
      visited.add(neighbor)
      queue.push([neighbor, newPath])
    }
  }
  return null
}

// ─── Data Loading ─────────────────────────────────────────────────────────────

/**
 * Loads graph_data.json (generated by export_graph_to_json.py) into the graph.
 * Pure graph loading — no localStorage, no UI side-effects.
 */
export const loadGraphData = async (): Promise<void> => {
  try {
    const res = await fetch(`${import.meta.env.BASE_URL}graph_data.json`)
    if (!res.ok) throw new Error('graph_data.json not found')
    const data = await res.json()

    for (const [student, interest] of data.students) {
      addEdge(nodeKey('student', student), nodeKey('interest', interest))
    }
    for (const [activity, interest] of data.activities) {
      addEdge(nodeKey('activity', activity), nodeKey('interest', interest))
    }
    if (data.registrations) {
      for (const [student, activity] of data.registrations) {
        addEdge(nodeKey('student', student), nodeKey('activity', activity))
      }
    }
    updateStats()
  } catch (err) {
    console.error('[useGraph] Failed to load graph data:', err)
  }
}
